/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ducdpg.email;

/**
 *
 * @author giadu
 */
public class BillEmail {

    public static String billEmail(String orderCode, String customer, String address, String email, String payment_method, 
            String payment_date, String amonut_paid) {
        String billDetail = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Invoice</title>\n"
                + "    <style>\n"
                + "        body {\n"
                + "            font-family: Arial, sans-serif;\n"
                + "            margin: 0;\n"
                + "            padding: 0;\n"
                + "        }\n"
                + "        .container {\n"
                + "            width: 600px;\n"
                + "            margin: 0 auto;\n"
                + "            padding: 20px;\n"
                + "            background-color: #f7f7f7;\n"
                + "        }\n"
                + "        .header img {\n"
                + "            display: block;\n"
                + "            margin: 0 auto;\n"
                + "        }\n"
                + "        .title {\n"
                + "            text-align: center;\n"
                + "            margin-top: 20px;\n"
                + "        }\n"
                + "        .title h2 {\n"
                + "            margin-bottom: 5px;\n"
                + "            color: #FF6B6B;\n"
                + "        }\n"
                + "        .title p {\n"
                + "            margin-top: 6px;\n"
                + "            color: #757575;\n"
                + "        }\n"
                + "        .line {\n"
                + "            border-top: 1px solid #ddd;\n"
                + "            margin-top: 20px;\n"
                + "        }\n"
                + "        .content {\n"
                + "            margin-top: 20px;\n"
                + "        }\n"
                + "        .content h4 span {\n"
                + "            color: #FF6B6B;\n"
                + "        }\n"
                + "        .content p strong {\n"
                + "            color: #747474;\n"
                + "        }\n"
                + "        .content table th {\n"
                + "            padding: 10px;\n"
                + "        }\n"
                + "        table {\n"
                + "            width: 100%;\n"
                + "            margin-top: 20px;\n"
                + "        }\n"
                + "        th {\n"
                + "            font-weight: bold;\n"
                + "            text-align: left;\n"
                + "        }\n"
                + "        .price {\n"
                + "            color: #10b981;\n"
                + "            font-size: 18px;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "        .footer {\n"
                + "            background-color: #ffe2e2;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .footer p {\n"
                + "            margin: 5px;\n"
                + "        }\n"
                + "        .footer p:first-child {\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div class=\"container\">\n"
                + "        <div class=\"header\">\n"
                + "            <img src=\"https://cdn.discordapp.com/attachments/1036663699458490408/1124165542157226104/lily-lane-logo-web.png\" alt=\"Company Logo\" width=\"100px\">\n"
                + "        </div>\n"
                + "        <div class=\"title\">\n"
                + "            <h2>Thank you for your order</h2>\n"
                + "            <p>We've received your payment and here is a summary:</p>\n"
                + "        </div>\n"
                + "        <div class=\"line\"></div>\n"
                + "        <div class=\"content\">\n"
                + "            <h4>Invoice <span>#"+orderCode+"</span></h4>\n"
                + "            <table>\n"
                + "                <tbody>\n"
                + "                    <tr>\n"
                + "                        <th>Customer:</th>\n"
                + "                        <td>"+ customer +"</td>\n"
                + "                    </tr>\n"
                + "                    <tr>\n"
                + "                        <th>Address:</th>\n"
                + "                        <td>"+ address +"</td>\n"
                + "                    </tr>\n"
                + "                    <tr>\n"
                + "                        <th>Email:</th>\n"
                + "                        <td>"+ email +"</td>\n"
                + "                    </tr>\n"
                + "                    <tr>\n"
                + "                        <th>Payment method:</th>\n"
                + "                        <td>"+ payment_method +"</td>\n"
                + "                    </tr>\n"
                + "                    <tr>\n"
                + "                        <th>Date of payment:</th>\n"
                + "                        <td>"+ payment_date +"</td>\n"
                + "                    </tr>\n"
                + "                </tbody>\n"
                + "            </table>\n"
                + "        </div>\n"
                + "        <div class=\"line\"></div>\n"
                + "        <table>\n"
                + "            <tr>\n"
                + "                <th>Total amount paid:</th>\n"
                + "                <td class=\"price\">"+ amonut_paid +" &#8363;</td>\n"
                + "            </tr>\n"
                + "        </table>\n"
                + "    </div>\n"
                + "    <div class=\"container footer\">\n"
                + "        <p>Lily Lane Store</p>\n"
                + "        <p>lilylanestore.flower@gmail.com</p>\n"
                + "        <p>289 Tran Hung Dao, District 1, Ho Chi Minh City</p>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
        return billDetail;
    }
}
